# Generated by Django 3.0.3 on 2020-02-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_date', models.DateTimeField()),
                ('report_date', models.DateTimeField()),
                ('product_type', models.CharField(max_length=200)),
                ('in_default', models.IntegerField()),
                ('healthy', models.IntegerField()),
                ('will_default', models.IntegerField()),
            ],
        ),
    ]
