# Generated by Django 3.0.3 on 2020-02-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counts',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
