# Generated by Django 3.0.3 on 2020-02-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_counts_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counts',
            name='load_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='counts',
            name='report_date',
            field=models.DateField(),
        ),
    ]
