# Generated by Django 3.0.3 on 2020-02-29 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200229_2343'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Counts',
            new_name='report_counts',
        ),
    ]
